\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory - EDE-Jackson_Joyner_Robinson
getwd()

# Load your packages
#install.packages(readxl)
#install.packages(tidyverse)
#install.packages(dplyr)
#install.packages(lubridate)
#install.packages(ggplot2)
#install.packages(sf)
#install.packages(mapview)
#install.packages(trend)
#install.packages(zoo)
#install.packages(kendall)
#install.packages(tseries)

library(readxl)
library(tidyverse)
library(dplyr)
library(lubridate)
library(ggplot2)
library(sf)
library(mapview)
library(trend)
library(zoo)
library(Kendall)
library(tseries)


#class(eGRID2020_Data)
#class(Gov_Data)
# Set your ggplot theme
# COME BACK TO THEME

# Load your datasets
eGRID2010 <- read_excel("Data/Raw/eGRID2010_Data.xls", 
    sheet = "PLNT10", skip = 4)
eGRID2012 <- read_excel("Data/Raw/eGRID2012_Data.xlsx", 
    sheet = "PLNT12", skip = 4)
eGRID2014 <- read_excel("Data/Raw/eGRID2014_Data.xlsx", 
    sheet = "PLNT14", skip = 1)
eGRID2016 <- read_excel("Data/Raw/egrid2016_Data.xlsx", 
                      sheet = "PLNT16", skip = 1)
eGRID2018 <- read_excel("Data/Raw/eGRID2018_Data.xlsx",
                      sheet = "PLNT18", skip = 1)
#REMOVE THIS LATER
#eGRID2019 <- read_excel("Data/Raw/egrid2019_Data.xlsx",
 #                     sheet = "PLNT19", skip = 1)
eGRID2020 <- read_excel("Data/Raw/eGRID2020_Data.xlsx",
                      sheet = "PLNT20", skip = 1)
Gov_Data <- read.csv("Data/Raw/US_Governors_1775_2020.csv")

```

# Wrangling eGRID

```{r Wrangle eGRID}
# selecting data for desired columns from imported eGRID datasets

#Note column "PLPFGNCT" for 2010 -- note that "PLFUELCT" was dropped and replaced
eGRID2010_sub <- eGRID2010 %>%
  mutate(YEAR="2010") %>%
  select(YEAR,PSTATABB,ORISPL,PNAME,PLPFGNCT,NAMEPCAP,LAT,LON)

eGRID2010_sub$PLFUELCT <- eGRID2010_sub$PLPFGNCT
eGRID2010_sub$PLPFGNCT <- NULL

#Note column "PLPFGNCT" for 2012 -- note that "PLFUELCT" was dropped and replaced
eGRID2012_sub <- eGRID2012 %>%
  mutate(YEAR="2012") %>%
  select(YEAR,PSTATABB,ORISPL,PNAME,PLPFGNCT,NAMEPCAP,LAT,LON)

eGRID2012_sub$PLFUELCT <- eGRID2012_sub$PLPFGNCT
eGRID2012_sub$PLPFGNCT <- NULL

eGRID2014_sub <- eGRID2014 %>%
  mutate(YEAR="2014") %>%
  select(YEAR,PSTATABB,ORISPL,PNAME,PLFUELCT,NAMEPCAP,LAT,LON)

eGRID2016_sub <- eGRID2016 %>%
  mutate(YEAR="2016") %>%
  select(YEAR,PSTATABB,ORISPL,PNAME,PLFUELCT,NAMEPCAP,LAT,LON)

eGRID2018_sub <- eGRID2018 %>%
  select(YEAR,PSTATABB,ORISPL,PNAME,PLFUELCT,NAMEPCAP,LAT,LON)

#REMOVE THIS LATER
#eGRID2019_sub <- eGRID2019 %>%
 # select(YEAR,PSTATABB,ORISPL,PNAME,PLFUELCT,NAMEPCAP,LAT,LON)

eGRID2020_sub <- eGRID2020 %>%
  select(YEAR,PSTATABB,ORISPL,PNAME,PLFUELCT,NAMEPCAP,LAT,LON)

# merging eGRID data, filtering for renewable fuels
eGRID_2010_2020 <- rbind(eGRID2010_sub,eGRID2012_sub,eGRID2014_sub,eGRID2016_sub,
      eGRID2018_sub,eGRID2020_sub)

# checking fuel types
unique(eGRID_2010_2020$PLFUELCT)

# filtering for desired fuel types
eGRID_2010_2020_RENEW <- filter(eGRID_2010_2020,PLFUELCT=="SOLAR"|PLFUELCT=="WIND"|PLFUELCT=="GEOTHERMAL"|
          PLFUELCT=="HYDRO"|PLFUELCT=="BIOMASS"|PLFUELCT=="NUCLEAR")

#Change year column to character
eGRID_2010_2020_RENEW$YEAR <- as.character(eGRID_2010_2020_RENEW$YEAR)
#eGRID_2010_2020_RENEW$YEAR <- year(eGRID_2010_2020_RENEW$YEAR)

# checking fuel types were filtered correctly
unique(eGRID_2010_2020_RENEW$PLFUELCT)

# checking to ensure all years of interest are present
unique(eGRID_2010_2020_RENEW$YEAR)

# saving process data as CSV
write_excel_csv(eGRID_2010_2020_RENEW, 
                path = "Data/Processed/eGRID_2010_2020_RENEW.csv")
```

#Wrangling Gov Data

```{r Wrangling Gov Data, include=FALSE}
#FIX THIS SHIT: MISSING 2010 and 2012 Years!!!!!!!!

#Filtering governor data for 2010 to 2020
Gov_Data_10_20 <- filter(Gov_Data,year >= 2010)

#Creating State abbreviation column for gov data
Gov_Data_State <- Gov_Data_10_20 %>%
  mutate(StateAbbreviation = state.abb[match(state, state.name)])

#Changing year to character
Gov_Data_State <- Gov_Data_State %>%
  mutate(year = as.character(year))

#Joining gov data with eGRID processed data
GOV_eGRID_10_20 <- left_join(eGRID_2010_2020_RENEW, Gov_Data_State, by = c("PSTATABB" = "StateAbbreviation", "YEAR" = "year"))

# dropping N/A's
drop_na(GOV_eGRID_10_20)

#Checking years of final dataset
unique(GOV_eGRID_10_20$YEAR)

#Checking fuel types of final dataset
unique(GOV_eGRID_10_20$PLFUELCT)

#Dataset information -- REVISIT THIS
dim(GOV_eGRID_10_20)
colnames(GOV_eGRID_10_20)

#Adding Final Processed file to processed folder
write_csv(GOV_eGRID_10_20, 
                path = "Data/Processed/GOV_eGRID_10_20.csv")
```
# Rationale and Research Questions



\newpage

# Dataset Information



\newpage

# Exploratory Analysis 



\newpage

# Analysis

```{r Graphical Analysis, include=FALSE}

#first_plot<- ggplot(GOV_eGRID_10_20, aes(x=YEAR,y=NAMEPCAP))+
 # geom_point()
#print(first_plot)


# spatial analysis
#eGRID_Gov.sf <- GOV_eGRID_10_20 %>% 
 # st_as_sf(coords = c('LON','LAT'),
  #         crs=4326)
#mapview(eGRID_Gov.sf, zcol="PLFUELCT")



```

## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
